#!/usr/bin/env bash

# Burp Suite installer for DEBAPPS
# Handles Burp Suite Community and Professional editions
# Requires: core/common.sh, lib/version.sh, lib/db.sh

set -euo pipefail

# Install Burp Suite
# Usage: install_burp "app_id"
install_burp() {
    local app_id="${1:-}"

    if [[ -z "$app_id" ]]; then
        print_message FAIL "install_burp requires an app_id"
        return 1
    fi

    # Get app configuration
    local app_config
    app_config=$(get_app_config "$app_id") || return 1

    local app_name
    app_name=$(echo "$app_config" | jq -r '.name')

    local app_desc
    app_desc=$(echo "$app_config" | jq -r '.description // ""')

    print_message INFOFULL "Installing ${app_name}"
    print_message INFO "${app_desc}"

    # Confirm installation
    if ! ui_confirm "Install ${app_name}" "Do you want to proceed with installation?"; then
        print_message INFO "Installation cancelled by user"
        return 0
    fi

    # Check if already installed
    if db_is_installed "$app_id" 2>/dev/null; then
        print_message WARN "${app_name} is already installed. Removing first..."
        remove_burp "$app_id" || {
            print_message FAIL "Failed to remove existing installation"
            return 1
        }
    fi

    # Resolve version and get download URL
    print_message INFO "Resolving latest version..."
    local version_info
    version_info=$(resolve_version "$app_id") || {
        print_message FAIL "Failed to resolve version for ${app_id}"
        return 1
    }

    local version
    version=$(echo "$version_info" | jq -r '.version')

    local download_url
    download_url=$(echo "$version_info" | jq -r '.download_url')

    local arch_type
    arch_type=$(echo "$version_info" | jq -r '.arch // "linux"')

    print_message PASS "Latest version: ${version}"

    # Get install location
    local install_location
    install_location=$(echo "$app_config" | jq -r '.install_location // "/opt/burpsuite"')

    # Download installer
    local installer_file="/tmp/burpsuite_${app_id}_installer.sh"

    print_message INFO "Downloading ${app_name} installer..."
    download_file "$installer_file" "$download_url" || {
        print_message FAIL "Download failed"
        return 1
    }

    # Make executable
    chmod +x "$installer_file"

    # Run installer in unattended mode
    print_message INFO "Running installer..."
    print_message WARN "This may take a few minutes..."

    # Create response file for unattended installation
    local response_file="/tmp/burpsuite_${app_id}_response.varfile"
    cat > "$response_file" << EOF
# Burp Suite unattended installation response file
# Generated by DEBAPPS
sys.installationDir=${install_location}
sys.languageId=en
sys.programGroupDisabled=false
EOF

    # Run installer
    if sudo "$installer_file" -q -varfile "$response_file"; then
        print_message PASS "${app_name} installed successfully"

        # Record in database
        db_insert_app "$app_id" "$app_name" "installer" "$version" "$install_location" "{\"installer\":true}"

        # Track installer directory
        db_insert_file "$app_id" "$install_location" "directory"

        # Cleanup
        rm -f "$installer_file" "$response_file" 2>/dev/null || true

        ui_success "Installation Complete" "${app_name} v${version} has been installed successfully"
    else
        print_message FAIL "Installer failed"
        rm -f "$installer_file" "$response_file" 2>/dev/null || true
        return 1
    fi
}

# Remove Burp Suite
# Usage: remove_burp "app_id"
remove_burp() {
    local app_id="${1:-}"

    if [[ -z "$app_id" ]]; then
        print_message FAIL "remove_burp requires an app_id"
        return 1
    fi

    # Get app configuration
    local app_config
    app_config=$(get_app_config "$app_id") || return 1

    local app_name
    app_name=$(echo "$app_config" | jq -r '.name')

    print_message WARN "Removing ${app_name}..."

    # Confirm removal
    if ! ui_confirm "Remove ${app_name}" "This will completely remove ${app_name}. Are you sure?"; then
        print_message INFO "Removal cancelled by user"
        return 0
    fi

    # Get install location from database or config
    local install_location
    if db_is_installed "$app_id" 2>/dev/null; then
        local db_info
        db_info=$(db_get_app "$app_id" 2>/dev/null | jq -r '.[0]')
        install_location=$(echo "$db_info" | jq -r '.install_location // ""')
    fi

    if [[ -z "$install_location" ]]; then
        install_location=$(echo "$app_config" | jq -r '.install_location // "/opt/burpsuite"')
    fi

    # Check if directory exists
    if [[ ! -d "$install_location" ]]; then
        print_message WARN "Installation directory not found: ${install_location}"

        # Remove from database if present
        if db_is_installed "$app_id" 2>/dev/null; then
            print_message INFO "Removing database entry..."
            db_remove_app "$app_id"
            print_message PASS "Database: Removed ${app_id} from tracking"
        fi

        ui_success "Removal Complete" "${app_name} has been removed from tracking"
        return 0
    fi

    # Run uninstaller if it exists
    local uninstaller="${install_location}/uninstall"
    if [[ -f "$uninstaller" ]]; then
        print_message INFO "Running uninstaller..."
        if sudo "$uninstaller" -q; then
            print_message PASS "Uninstaller completed successfully"
        else
            print_message WARN "Uninstaller failed, removing directory manually..."
            sudo rm -rf "$install_location"
        fi
    else
        # Manually remove directory
        print_message INFO "Removing installation directory: ${install_location}"
        sudo rm -rf "$install_location"
    fi

    # Remove from database
    if db_is_installed "$app_id" 2>/dev/null; then
        db_remove_app "$app_id"
        print_message PASS "Database: Removed ${app_id} from tracking"
    fi

    ui_success "Removal Complete" "${app_name} has been removed successfully"
}

# Reinstall Burp Suite
# Usage: reinstall_burp "app_id"
reinstall_burp() {
    local app_id="${1:-}"

    if [[ -z "$app_id" ]]; then
        print_message FAIL "reinstall_burp requires an app_id"
        return 1
    fi

    local app_name
    app_name=$(get_app_name "$app_id")

    print_message INFO "Reinstalling ${app_name}..."

    # Remove first
    remove_burp "$app_id" || {
        print_message WARN "Removal failed, attempting fresh install anyway..."
    }

    # Install
    install_burp "$app_id"
}

# Upgrade Burp Suite (same as reinstall)
# Usage: upgrade_burp "app_id"
upgrade_burp() {
    local app_id="${1:-}"

    reinstall_burp "$app_id"
}
